version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '8010:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=farmacia
    volumes:
      - 'ifood_pg_data:/bitnami/postgresql'

volumes:
  ifood_pg_data: